// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    RollContainer: typeof import('./src/components/RollContainer.vue')['default']
  }
}

export { }
