// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterItem: typeof import('./src/components/RouterItem.vue')['default']
    Src: typeof import('./src/components/SeamlessScroll/src/index.vue')['default']
  }
}

export { }
